DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(ID INT PRIMARY KEY, 
 FIRSTNAME VARCHAR,
 LASTNAME VARCHAR,
 DATEOFJOINING DATETIME
 );
 
 
CREATE TABLE PAYMENT
(PAYMENTID INT PRIMARY KEY AUTO_INCREMENT, 
 AMOUNT VARCHAR,
 PAYMENTDATE DATETIME,
 DESCRIPTION VARCHAR,
 USER_ID VARCHAR
 );
 
alter table PAYMENT add constraint PAYMNT_USER_ID foreign key (USER_ID) references USER(id);